[package]
name = "censoredpi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
criterion = "0.5.1"
futures = "0.3.30"

[[bench]]
name = "bench_censorship"
harness = false