[package]
name = "censoredpi-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
censoredpi = { path = "../censoredpi-rs" }
futures = "0.3.30"
jemalloc-ctl = "0.5.4"
jemallocator = "0.5.4"
